// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCElFa2kFsjRxsXRf-_3wpU-CUJTA-6JwY',
    appId: '1:952254846828:web:b7f436cdbfeeb6a5668549',
    messagingSenderId: '952254846828',
    projectId: 'intollerance-app',
    authDomain: 'intollerance-app.firebaseapp.com',
    storageBucket: 'intollerance-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4qy5Eg1nI6JRcKIRg6BwBwPOivP58SgE',
    appId: '1:952254846828:android:777fd6bdb22761f2668549',
    messagingSenderId: '952254846828',
    projectId: 'intollerance-app',
    storageBucket: 'intollerance-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuCClBbud0PbOIB4kCN3eMNUMUt2tgQhs',
    appId: '1:952254846828:ios:d57cf6a2f5b5a93b668549',
    messagingSenderId: '952254846828',
    projectId: 'intollerance-app',
    storageBucket: 'intollerance-app.firebasestorage.app',
    iosBundleId: 'com.example.intolApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuCClBbud0PbOIB4kCN3eMNUMUt2tgQhs',
    appId: '1:952254846828:ios:d57cf6a2f5b5a93b668549',
    messagingSenderId: '952254846828',
    projectId: 'intollerance-app',
    storageBucket: 'intollerance-app.firebasestorage.app',
    iosBundleId: 'com.example.intolApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCElFa2kFsjRxsXRf-_3wpU-CUJTA-6JwY',
    appId: '1:952254846828:web:836b0efcb080bd63668549',
    messagingSenderId: '952254846828',
    projectId: 'intollerance-app',
    authDomain: 'intollerance-app.firebaseapp.com',
    storageBucket: 'intollerance-app.firebasestorage.app',
  );
}
